---
id: MyModel0001
name: TruckingModel
description: A model for simulating a trucking process with stockpiles and trucks.

loggers:
  - name: StockpileLogger
    log_type: ArrayStockLog
    log_path: stockpile_logs.csv
  - name: TruckQueueLogger
    log_type: QueueStockLog
    log_path: truck_queue_logs.csv
  - name: ProcessLogger
    log_type: TruckingProcessLog
    log_path: truck_movement_logs.csv
  - name: TruckStockLogger
    log_type: TruckAndOreStockLog
    log_path: truck_stock_logs.csv`

components:
  - name: Stockpile1
    type: ArrayStock123
    loggers: [StockpileLogger]

  - name: LoadProcess
    type: LoadingProcess
    loggers: [ProcessLogger]
    
  - name: LoadedTrucks
    type: TruckStock
    loggers: [TruckQueueLogger]

  - name: LoadedTruckMovement
    type: TruckMovementProcess
    loggers: [ProcessLogger]

  - name: ReadyToDump
    type: TruckStock
    loggers: [TruckQueueLogger]

  - name: DumpProcess
    type: DumpingProcess
    loggers: [ProcessLogger]

  - name: Stockpile2
    type: ArrayStock
    loggers: [StockpileLogger]

  - name: EmptyTrucks
    type: TruckStock
    loggers: [TruckQueueLogger]

  - name2: EmptyTruckMovement
    type: TruckMovementProcess
    loggers: [ProcessLogger]

  - name: ReadyToLoad
    type: TruckStock
    loggers: [TruckQueueLogger]

connections:
  - [Stockpile1, LoadProcess]
  - [ReadyToLoad, LoadProcess]
  - [LoadProcess, LoadedTrucks]
  - [LoadedTrucks, LoadedTruckMovement]
  - [LoadedTruckMovement, ReadyToDump]
  - [ReadyToDump, DumpProcess]
  - [DumpProcess, Stockpile2]
  - [DumpProcess, EmptyTrucks]
  - [EmptyTrucks, EmptyTruckMovement]
  - [EmptyTruckMovement, ReadyToLoad]

