---
id: MyModel0001
name: TruckingModel
description: A model for simulating a trucking process with stockpiles and trucks.

loggers:
  - name: StockpileLogger
    record_type: ArrayStockLog
    max_length: 100000
    log_path: stockpile_logs.csv
  - name: TruckQueueLogger
    record_type: QueueStockLog
    max_length: 100000
    log_path: truck_queue_logs.csv
  - name: ProcessLogger
    record_type: TruckingProcessLog
    max_length: 100000
    log_path: truck_movement_logs.csv
  - name: TruckStockLogger
    record_type: TruckAndOreStockLog
    max_length: 100000
    log_path: truck_stock_logs.csv

components:
  - name: Stockpile1
    type: ArrayStock
    loggers: [StockpileLogger]
    vec: [800000, 600000, 400000, 200000, 0]
    max_capacity: 2000000
    low_capacity: 1000


  - name: LoadProcess
    type: LoadingProcess
    loggers: [ProcessLogger]
    load_time_dist_secs:
      type: TruncNormal
      mean: 40
      std: 10
      min: 10
      max: null
    load_quantity_dist:
      type: Uniform
      min: 70
      max: 130
    
  - name: LoadedTrucks
    type: TruckStock
    loggers: [TruckQueueLogger]

  - name: LoadedTruckMovement
    type: TruckMovementProcess
    loggers: [ProcessLogger]
    travel_time_dist_secs:
      type: Triangular
      min: 100
      max: 200
      mode: 120

  - name: ReadyToDump
    type: TruckStock
    loggers: [TruckQueueLogger]

  - name: DumpProcess
    type: DumpingProcess
    loggers: [ProcessLogger]
    dump_time_dist_secs:
      type: TruncNormal
      mean: 30
      std: 8
      min: 14
      max: 46

  - name: Stockpile2
    type: ArrayStock
    loggers: [StockpileLogger]
    vec: [0, 0, 0, 0, 0]
    max_capacity: 2000000
    low_capacity: 1000

  - name: EmptyTrucks
    type: TruckStock
    loggers: [TruckQueueLogger]

  - name: EmptyTruckMovement
    type: TruckMovementProcess
    loggers: [ProcessLogger]
    travel_time_dist_secs:
      type: Triangular
      min: 50
      max: 100
      mode: 60

  - name: ReadyToLoad
    type: TruckStock
    loggers: [TruckQueueLogger]

connections:
  - upstream: Stockpile1
    downstream: LoadProcess
  - upstream: ReadyToLoad
    downstream: LoadProcess
  - upstream: LoadProcess
    downstream: LoadedTrucks
  - upstream: LoadedTrucks
    downstream: LoadedTruckMovement
  - upstream: LoadedTruckMovement
    downstream: ReadyToDump
  - upstream: ReadyToDump
    downstream: DumpProcess
  - upstream: DumpProcess
    downstream: Stockpile2
  - upstream: DumpProcess
    downstream: EmptyTrucks
  - upstream: EmptyTrucks
    downstream: EmptyTruckMovement
  - upstream: EmptyTruckMovement
    downstream: ReadyToLoad

