[package]
name = "quokkasim"
version = "0.1.0"
edition = "2024"

[lib]
name = "quokkasim"
path = "src/lib.rs"

[dependencies]
nexosim = "0.3.0-beta.0"
tai-time = { version = "0.3.3", features = ["serde"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.134"
rand_distr = "0.4.3"
rand = { version = "0.8.5", features = [ "small_rng" ] }
futures = "0.3.31"
csv = "1.3.1"